/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function fibonacci(n: number): number
export function runCallback(callback: (s: string) => void): void
export class QueryEngine {
  constructor(queryName: string)
  get queryName(): string
  set queryName(queryName: string)
}
